name: test and deploy react app to ubuntu

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v8

    - name: Use Node.js
      uses: actions/setup-node@v8
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
    - name:
      run: npm run test
